# SPDX-FileCopyrightText: 2006 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    maven-plugins:
      patterns:
        - "org.apache.maven.plugins:*"
        - "org.codehaus.mojo:*"
        - "org.sonatype:*"
